name: Terraform Multicloud

on:
  push:
    branches:
    - development

env:
  TERRAFORM_VERSION  : 1.9.7
  ARM_CLIENT_ID      : ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET  : ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID      : ${{ secrets.ARM_TENANT_ID }}

jobs:
  ci-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token    : ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region           : us-east-1
    - run: terraform -chdir=./terraform/aws init
    - run: terraform -chdir=./terraform/aws validate
    - run: terraform -chdir=./terraform/azure init
    - run: terraform -chdir=./terraform/azure validate
  cd-aws:
    name: Deploy on AWS
    needs: ci-test
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token    : ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region           : us-east-1
    - run: terraform -chdir=./terraform/aws init
    - run: terraform -chdir=./terraform/aws plan -destroy -out tfplan
    - run: terraform -chdir=./terraform/aws apply tfplan
    - run: terraform -chdir=./terraform/aws show
  cd-azure:
    name: Deploy on Azure
    needs: ci-test
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION
    - uses: actions/checkout@v4
    - run: terraform -chdir=./terraform/azure init
    - run: terraform -chdir=./terraform/azure plan -destroy -out tfplan
    - run: terraform -chdir=./terraform/azure apply tfplan
    - run: terraform -chdir=./terraform/azure show